import { Hono } from "hono";
import type { Context } from "hono";
import type { WSContext } from "hono/ws";
import { createNodeWebSocket } from "@hono/node-ws";
import { serve } from "@hono/node-server";
import { serveStatic } from "@hono/node-server/serve-static";
import debug from "debug";

const log = debug("realtime-monitor:server");

const app = new Hono();
const { injectWebSocket, upgradeWebSocket } = createNodeWebSocket({ app });

function uid(): string {
  return Math.random().toString(36).slice(2, 10);
}

function safeSend(ws: WSContext, data: unknown): void {
  try {
    ws.send(JSON.stringify(data));
  } catch (err) {
    log("ws send error:", err);
  }
}

// ── Conversation store ────────────────────────────────────────────────────────

interface Conversation {
  id: string;
  log: unknown[];
  unityConnected: boolean;
  createdAt: number;
  lastEventAt: number;
}

/** All conversations, keyed by sessionId generated by Unity. */
const conversations = new Map<string, Conversation>();

/** Browser WebSocket clients per conversation. */
const sessionBrowsers = new Map<string, Set<WSContext>>();

function getOrCreateConv(sessionId: string): Conversation {
  let conv = conversations.get(sessionId);
  if (!conv) {
    conv = { id: sessionId, log: [], unityConnected: false, createdAt: Date.now(), lastEventAt: Date.now() };
    conversations.set(sessionId, conv);
    sessionBrowsers.set(sessionId, new Set());
    log("new conversation:", sessionId);
  }
  return conv;
}

function broadcastToSession(sessionId: string, data: unknown): void {
  const browsers = sessionBrowsers.get(sessionId);
  if (!browsers) return;
  for (const ws of browsers) safeSend(ws, data);
}

function pushConvLog(conv: Conversation, entry: unknown): void {
  conv.log.push(entry);
  conv.lastEventAt = Date.now();
  broadcastToSession(conv.id, entry);
}

// ── Unity WebSocket endpoint (/unity-ws?sessionId=<id>) ───────────────────────
// Unity Server connects here for each session and forwards every packet
// sent to / received from the OpenAI Realtime API.

app.get(
  "/unity-ws",
  upgradeWebSocket((c: Context) => {
    const sessionId = c.req.query("sessionId") || uid();
    const conv = getOrCreateConv(sessionId);
    conv.unityConnected = true;

    return {
      onOpen(_event: Event, _ws: WSContext) {
        log("unity connected, session:", sessionId);
      },

      onMessage(event: MessageEvent, _ws: WSContext) {
        let msg: { type: string; dir?: string; data?: unknown; state?: string; error?: string };
        try {
          msg = JSON.parse(event.data.toString()) as typeof msg;
        } catch {
          return;
        }

        switch (msg.type) {
          case "status":
            pushConvLog(conv, { type: "status", state: msg.state, error: msg.error });
            break;

          case "log":
            pushConvLog(conv, { type: "log", id: uid(), ts: Date.now(), dir: msg.dir, data: msg.data });
            break;
        }
      },

      onClose() {
        log("unity disconnected, session:", sessionId);
        conv.unityConnected = false;
        pushConvLog(conv, { type: "status", state: "disconnected" });
      },

      onError(event: Event) {
        log("unity ws error:", event);
      },
    };
  })
);

// ── Browser WebSocket endpoint (/ws?conv=<id>) ────────────────────────────────
// Browser connects here to watch a specific conversation in real-time.

app.get(
  "/ws",
  upgradeWebSocket((c: Context) => {
    const sessionId = c.req.query("conv") || "";
    let clientWs: WSContext | null = null;

    return {
      onOpen(_event: Event, ws: WSContext) {
        log("browser connected to conv:", sessionId || "(none)");
        clientWs = ws;

        if (!sessionId) {
          // No conv param — send the conversation list immediately
          const list = buildConvList();
          safeSend(ws, { type: "conv_list", conversations: list });
          return;
        }

        const conv = getOrCreateConv(sessionId);
        const browsers = sessionBrowsers.get(sessionId)!;
        browsers.add(ws);

        // Replay full event history to the new browser client
        for (const entry of conv.log) {
          safeSend(ws, entry);
        }

        // Sync current connection state
        safeSend(ws, {
          type: "status",
          state: conv.unityConnected ? "connected" : "disconnected",
        });
      },

      onMessage(event: MessageEvent, _ws: WSContext) {
        let msg: { type: string };
        try {
          msg = JSON.parse(event.data.toString()) as typeof msg;
        } catch {
          return;
        }

        if (msg.type === "clear" && sessionId) {
          const conv = conversations.get(sessionId);
          if (conv) {
            conv.log.length = 0;
            broadcastToSession(sessionId, { type: "clear" });
            log("conv log cleared:", sessionId);
          }
        }
      },

      onClose() {
        log("browser disconnected from conv:", sessionId || "(none)");
        if (clientWs && sessionId) {
          sessionBrowsers.get(sessionId)?.delete(clientWs);
        }
        clientWs = null;
      },

      onError(event: Event) {
        log("browser ws error:", event);
      },
    };
  })
);

// ── REST: conversation list ──────────────────────────────────────────────────

function buildConvList() {
  return [...conversations.values()]
    .map((c) => ({
      id: c.id,
      unityConnected: c.unityConnected,
      eventCount: c.log.length,
      createdAt: c.createdAt,
      lastEventAt: c.lastEventAt,
    }))
    .sort((a, b) => b.createdAt - a.createdAt);
}

app.get("/api/conversations", (c: Context) => {
  return c.json(buildConvList());
});

// ── Static files ──────────────────────────────────────────────────────────────

app.use(
  "/*",
  serveStatic({
    root: "./public/",
    onFound(_path, c) {
      c.header("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");
    },
  })
);

// ── Start server ──────────────────────────────────────────────────────────────

const PORT = parseInt(process.env.PORT ?? "3681", 10);
const server = serve({ fetch: app.fetch, port: PORT }, (info) => {
  log(`online → http://localhost:${info.port}`);
});
injectWebSocket(server);

export { app };
