services:
  3dog-node-backend:
    build:
      context: ..
      dockerfile: Dockerfile
    image: 3dog-node-backend:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - path: ../.env
        required: false
    ports:
      - "3600:3600"
      - "3601:3601"
    networks:
      - 3dog-node-backend-net

networks:
  3dog-node-backend-net:
    driver: bridge
