name: Test

on:
  pull_request:
  push:
    branches-ignore:
      - master
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/craft3d
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: services/craft3d/package-lock.json

      - run: npm run deps:dev
      - run: npm test
